jest.config.js
packages/primitives/switch/tests/switch.test.tsx
packages/utilities/use-toggle/README.md
packages/utilities/use-toggle/package.json
packages/utilities/use-toggle/src/index.ts
packages/utilities/use-toggle/src/use-toggle.ts
packages/utilities/use-toggle/tests/use-toggle.test.ts
tsconfig.json
yarn.lock

New useToggle hook added to Raddix utility hooks

feat: add use toggle

---

packages/primitives/switch/README.md
packages/primitives/switch/package.json
packages/primitives/switch/src/switch.ts
packages/primitives/switch/src/switch.utils.ts
packages/primitives/switch/src/types.ts
packages/primitives/switch/stories/switch.css
packages/primitives/switch/stories/switch.stories.mdx
packages/primitives/switch/tests/switch.test.tsx
yarn.lock

Added strong typing to the as prop and switchProps property, removed the fusion-props package, and improved switch performance

feat(switch): improved performance and typing

---

.gitignore

update `.gitignore` to ignore [.idea](https://rider-support.jetbrains.com/hc/en-us/articles/207097529-What-is-the-idea-folder-) files  from IntelliJ’s editors

chore(gitignore): add .idea

---

packages/primitives/checkbox/src/index.ts

Change the undefined type CheckboxRootBase to the type UseCheckboxProps

fix(checkbox): undefined export type

---

.github/CONTRIBUTING.md

Closes 
information about the folder structure

docs(contributing): add considerations

---

packages/interactions/use-keyboard/src/keys.ts
packages/interactions/use-keyboard/src/use-keyboard.ts
packages/interactions/use-keyboard/tests/use-keyboard.test.tsx
packages/primitives/checkbox/src/Checkboxv2.tsx
packages/primitives/checkbox/src/checkbox.ts
packages/primitives/checkbox/src/checkbox.utils.ts
packages/primitives/checkbox/src/index.ts
packages/primitives/checkbox/src/types.ts
packages/primitives/switch/src/index.ts
packages/primitives/switch/src/switch.ts
packages/primitives/switch/src/switch.utils.ts
packages/primitives/switch/src/types.ts
packages/primitives/switch/tests/switch.test.tsx
packages/utilities/use-toggle/src/use-toggle.ts

refactor the code with the new typescript eslint rules

refactor: apply the rules of eslint and ts

---

.github/workflows/main.yml
package.json

Add linter control in continuous integration

chore: add linter check

---

.github/workflows/main.yml
package.json

Add prettier formatting scripts and verify in continuous integration

chore: add format check

---

.eslintrc.js
.gitignore
package.json
packages/interactions/use-keyboard/package.json
packages/primitives/switch/package.json
packages/utilities/use-toggle/package.json
pnpm-lock.yaml
turbo.json

Add Turborepo to boost task execution.
- Parallel execution
- Content-aware hashing
- Incremental builds

chore: add turborepo

---

.github/workflows/main.yml

Add build workflow in GitHub Actions

ci: add build workflow

---

.gitignore
clean-package.config.json
package.json
packages/interactions/use-keyboard/package.json
packages/primitives/switch/package.json
packages/utilities/use-toggle/package.json
pnpm-lock.yaml

`clean-package` is used for removing development configuration from 'package.json' before publishing the package to NPM.

chore: add `clean-package` tool

---

.github/workflows/release.yml

Add Changesets GitHub action for publishing automatize

chore: publishing automatize

---

.storybook/main.ts

change config paths of stories `.stories.mdx` to `.mdx`

fix: change config paths of stories

---

packages/primitives/switch/package.json
pnpm-lock.yaml

Remove targets and publishConfig  options of package.json

fix(switch): remove targets and publishConfig options

---

.changeset/spicy-ducks-press.md
packages/interactions/use-keyboard/src/use-keyboard.ts
packages/interactions/use-keyboard/tests/use-keyboard.test.tsx

Closes #41 
Fixed bug that settings options are not applied

fix(useKeyboard): settings options are not applied

---

.changeset/eighty-pens-reflect.md
packages/utilities/use-media-query/package.json

chore: add keywords in package.json

---

.changeset/orange-jeans-rest.md
packages/utilities/use-count-down/README.md
packages/utilities/use-count-down/src/index.ts
packages/utilities/use-count-down/tests/use-count-down.test.ts

Added a new API that provides more flexibility and also improved the countdown logic

feat(useCountDown): new improved API

---

.changeset/lazy-camels-dress.md
packages/utilities/use-count-down/src/index.ts
packages/utilities/use-count-down/tests/use-count-down.test.ts

Add countdown status indicators:
- isRunning: If the countdown is running it returns true, if it is paused it returns false.
- isFinished: If the countdown is over, it returns true, otherwise it returns false.

feat(useCountDown): add indicators of status

---

.changeset/fast-peaches-move.md
packages/utilities/use-counter/README.md
packages/utilities/use-counter/package.json
packages/utilities/use-counter/src/index.ts
packages/utilities/use-counter/tests/use-counter.test.ts
pnpm-lock.yaml

`useCounter` is a custom hook that manage a counter value with minimum and maximum limits.

feat: add useCounter hook

---

.changeset/fluffy-waves-design.md
packages/hooks/use-timeout/README.md
packages/hooks/use-timeout/src/index.ts
packages/hooks/use-timeout/tests/use-timeout.test.ts

- Added two new return functions: `reset` and `run`
- Added a new `immediate` option
- Added null type in the `delay` option

feat(useTimeout): API improved

---

.changeset/little-spiders-sparkle.md
packages/hooks/use-interval/src/index.ts
packages/hooks/use-interval/tests/use-interval.test.ts

Add null type in the delay option

feat(useInterval): add null type in the delay option

---

.changeset/hot-donkeys-shop.md
packages/hooks/use-event-listener/README.md
packages/hooks/use-event-listener/package.json
packages/hooks/use-event-listener/src/index.ts
packages/hooks/use-event-listener/tests/index.test.ts
pnpm-lock.yaml

A hook that enables you to add event listeners to a target element or document.

feat: add useEventListener hook

---

packages/hooks/use-event-listener/src/index.ts

Add variables for window and document with SSR support

feat(useEventListener): add variables for SSR support

---

.changeset/stale-mails-mate.md
packages/hooks/use-window-size/README.md
packages/hooks/use-window-size/package.json
packages/hooks/use-window-size/src/index.ts
packages/hooks/use-window-size/tests/index.test.ts
pnpm-lock.yaml

A hook that track the dimensions of the browser window.

feat: add useWindowSize hook

---

.changeset/wild-socks-type.md
packages/hooks/use-event-listener/src/index.ts

Add null type in first parameter of useEventListener

feat(useEventListener): Add null type in first parameter

---

.changeset/yellow-experts-beam.md
packages/hooks/use-scroll-position/README.md
packages/hooks/use-scroll-position/package.json
packages/hooks/use-scroll-position/src/index.ts
packages/hooks/use-scroll-position/tests/use-scroll-position.test.ts
pnpm-lock.yaml

A hook to listen to the scroll position of the current window or element.

feat: add useScrollPosition hook

---

.changeset/old-paws-watch.md
packages/hooks/use-debounce/README.md
packages/hooks/use-event-listener/README.md
packages/hooks/use-scroll-position/README.md
packages/hooks/use-window-size/README.md

docs: fix documentation link

---

templates/create-hook/README.md.hbs
templates/create-hook/tests/index.test.ts.hbs

Update documentation link and test file name

chore: update create-hook template

---

.changeset/silly-lies-sin.md
packages/hooks/use-click-outside/README.md
packages/hooks/use-click-outside/package.json
packages/hooks/use-count-down/README.md
packages/hooks/use-count-down/package.json
packages/hooks/use-counter/README.md
packages/hooks/use-counter/package.json
packages/hooks/use-debounce/README.md
packages/hooks/use-debounce/package.json
packages/hooks/use-event-listener/README.md
packages/hooks/use-event-listener/package.json
packages/hooks/use-interval/README.md
packages/hooks/use-interval/package.json
packages/hooks/use-keyboard/README.md
packages/hooks/use-keyboard/package.json
packages/hooks/use-media-query/README.md
packages/hooks/use-scroll-position/README.md
packages/hooks/use-scroll-position/package.json
packages/hooks/use-scroll-spy/README.md
packages/hooks/use-scroll-spy/package.json
packages/hooks/use-switch/README.md
packages/hooks/use-timeout/README.md
packages/hooks/use-timeout/package.json
packages/hooks/use-timeout/src/index.ts
packages/hooks/use-toggle/README.md
packages/hooks/use-toggle/package.json
packages/hooks/use-window-size/README.md
packages/hooks/use-window-size/package.json
templates/create-hook/README.md.hbs
templates/create-hook/package.json.hbs

Update the url with the new domain of the documentation website

feat: Update documentation URLs

---

packages/hooks/use-click-outside/docs/en.mdx
packages/hooks/use-click-outside/docs/es.mdx
packages/hooks/use-count-down/docs/en.mdx
packages/hooks/use-count-down/docs/es.mdx
packages/hooks/use-counter/docs/en.mdx
packages/hooks/use-counter/docs/es.mdx
packages/hooks/use-event-listener/docs/en.mdx
packages/hooks/use-event-listener/docs/es.mdx
packages/hooks/use-interval/docs/en.mdx
packages/hooks/use-interval/docs/es.mdx
packages/hooks/use-keyboard/docs/en.mdx
packages/hooks/use-keyboard/docs/es.mdx
packages/hooks/use-media-query/docs/en.mdx
packages/hooks/use-media-query/docs/es.mdx
packages/hooks/use-scroll-position/docs/en.mdx
packages/hooks/use-scroll-position/docs/es.mdx
packages/hooks/use-scroll-spy/docs/en.mdx
packages/hooks/use-scroll-spy/docs/es.mdx
packages/hooks/use-timeout/docs/en.mdx
packages/hooks/use-timeout/docs/es.mdx
packages/hooks/use-toggle/docs/en.mdx
packages/hooks/use-toggle/docs/es.mdx
packages/hooks/use-window-size/docs/en.mdx
packages/hooks/use-window-size/docs/es.mdx

Add hooks documentation from the website repository

feat: add docs from the core repository

---

docs/_config.json
docs/en/use-click-outside.mdx
docs/en/use-count-down.mdx
docs/en/use-counter.mdx
docs/en/use-event-listener.mdx
docs/en/use-interval.mdx
docs/en/use-keyboard.mdx
docs/en/use-media-query.mdx
docs/en/use-scroll-position.mdx
docs/en/use-scroll-spy.mdx
docs/en/use-timeout.mdx
docs/en/use-toggle.mdx
docs/en/use-window-size.mdx
docs/es/use-click-outside.mdx
docs/es/use-count-down.mdx
docs/es/use-counter.mdx
docs/es/use-event-listener.mdx
docs/es/use-interval.mdx
docs/es/use-keyboard.mdx
docs/es/use-media-query.mdx
docs/es/use-scroll-position.mdx
docs/es/use-scroll-spy.mdx
docs/es/use-timeout.mdx
docs/es/use-toggle.mdx
docs/es/use-window-size.mdx

docs: update hooks description

---

.changeset/tender-mirrors-taste.md
docs/_config.json
docs/en/use-first-render.mdx
docs/es/use-first-render.mdx
packages/hooks/use-first-render/README.md
packages/hooks/use-first-render/package.json
packages/hooks/use-first-render/src/index.ts
packages/hooks/use-first-render/tests/index.test.ts
pnpm-lock.yaml

A hook that returns a boolean that is true only on first render.

feat: add useFirstRender hook

---

.changeset/green-planets-tickle.md
.eslintrc.js
docs/_config.json
docs/en/use-clipboard.mdx
docs/es/use-clipboard.mdx
packages/hooks/use-clipboard/README.md
packages/hooks/use-clipboard/package.json
packages/hooks/use-clipboard/src/index.ts
packages/hooks/use-clipboard/tests/index.test.ts
pnpm-lock.yaml

A hook that provides copy to clipboard functionality.

feat: add useClipboard hook

---

.changeset/silly-kids-obey.md
docs/_config.json
docs/en/use-boolean.mdx
docs/es/use-boolean.mdx
packages/hooks/use-boolean/README.md
packages/hooks/use-boolean/package.json
packages/hooks/use-boolean/src/index.ts
packages/hooks/use-boolean/tests/index.test.ts
pnpm-lock.yaml

A hook that manages a boolean value with useful utility functions.

feat: add useBoolean hook

---

.changeset/slow-chicken-drive.md
docs/_config.json
docs/en/use-battery.mdx
docs/es/use-battery.mdx
packages/hooks/use-battery/README.md
packages/hooks/use-battery/package.json
packages/hooks/use-battery/src/index.ts
packages/hooks/use-battery/tests/index.test.ts
pnpm-lock.yaml

A hook that Tracking the battery status of the device.

feat: add useBattery hook

---

docs/_config.json
docs/en/use-debounce.mdx
docs/es/use-debounce.mdx

Add documentation for useDebounce hook

docs: useDebounce hook

---

.changeset/seven-meals-visit.md
docs/_config.json
docs/en/use-client.mdx
docs/en/use-debounce.mdx
docs/es/use-client.mdx
docs/es/use-debounce.mdx
packages/hooks/use-client/README.md
packages/hooks/use-client/package.json
packages/hooks/use-client/src/index.ts
packages/hooks/use-client/tests/index.test.ts
pnpm-lock.yaml

A hook that determine whether the code is running on the client-side.

feat: add useClient hook

---

.changeset/sweet-books-brake.md
docs/_config.json
docs/en/use-isomorphic-effect.mdx
docs/es/use-isomorphic-effect.mdx
packages/hooks/use-isomorphic-effect/README.md
packages/hooks/use-isomorphic-effect/package.json
packages/hooks/use-isomorphic-effect/src/index.ts
packages/hooks/use-isomorphic-effect/tests/index.test.ts
pnpm-lock.yaml

Alias for useLayoutEffect in browser and useEffect on the server side.

feat: add useIsomorphicEffect hook

---

.changeset/spicy-peaches-decide.md
docs/_config.json
docs/en/use-previous.mdx
docs/es/use-previous.mdx
packages/hooks/use-previous/README.md
packages/hooks/use-previous/package.json
packages/hooks/use-previous/src/index.ts
packages/hooks/use-previous/tests/index.test.ts
pnpm-lock.yaml

A hook that returns previous value of given state.

feat: add usePrevious hook
